package org.dieschnittstelle.jee.esa.uebungen.jws4;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2014-11-24T22:31:33.099+01:00
 * Generated source version: 2.4.6
 * 
 */
@WebService(targetNamespace = "http://dieschnittstelle.org/jee/esa/uebungen/jws4", name = "ProductCRUDWebService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ProductCRUDWebService {

    @WebResult(name = "createProductResponse", targetNamespace = "http://dieschnittstelle.org/jee/esa/uebungen/jws4", partName = "createProductResponse")
    @WebMethod
    public AbstractProduct createProduct(
        @WebParam(partName = "createProduct", name = "createProduct", targetNamespace = "http://dieschnittstelle.org/jee/esa/uebungen/jws4")
        AbstractProduct createProduct
    );

    @WebResult(name = "readAllProductsResponse", targetNamespace = "http://dieschnittstelle.org/jee/esa/uebungen/jws4", partName = "readAllProductsResponse")
    @WebMethod
    public AbstractProductArray readAllProducts();
}
