package org.dieschnittstelle.jee.esa.uebungen.add3;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2015-01-23T00:16:05.757+01:00
 * Generated source version: 2.4.6
 * 
 */
@WebService(targetNamespace = "http://dieschnittstelle.org/jee/esa/uebungen/add3", name = "StockSystem")
@XmlSeeAlso({ObjectFactory.class})
public interface StockSystem {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "fuckYou", targetNamespace = "http://dieschnittstelle.org/jee/esa/uebungen/add3", className = "org.dieschnittstelle.jee.esa.uebungen.add3.FuckYou")
    @WebMethod
    @ResponseWrapper(localName = "fuckYouResponse", targetNamespace = "http://dieschnittstelle.org/jee/esa/uebungen/add3", className = "org.dieschnittstelle.jee.esa.uebungen.add3.FuckYouResponse")
    public int fuckYou(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getUnitsOnStock", targetNamespace = "http://dieschnittstelle.org/jee/esa/uebungen/add3", className = "org.dieschnittstelle.jee.esa.uebungen.add3.GetUnitsOnStock")
    @WebMethod
    @ResponseWrapper(localName = "getUnitsOnStockResponse", targetNamespace = "http://dieschnittstelle.org/jee/esa/uebungen/add3", className = "org.dieschnittstelle.jee.esa.uebungen.add3.GetUnitsOnStockResponse")
    public int getUnitsOnStock(
        @WebParam(name = "arg0", targetNamespace = "")
        org.dieschnittstelle.jee.esa.uebungen.add3.AbstractProduct arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1
    );

    @RequestWrapper(localName = "addToStock", targetNamespace = "http://dieschnittstelle.org/jee/esa/uebungen/add3", className = "org.dieschnittstelle.jee.esa.uebungen.add3.AddToStock")
    @WebMethod
    @ResponseWrapper(localName = "addToStockResponse", targetNamespace = "http://dieschnittstelle.org/jee/esa/uebungen/add3", className = "org.dieschnittstelle.jee.esa.uebungen.add3.AddToStockResponse")
    public void addToStock(
        @WebParam(name = "arg0", targetNamespace = "")
        org.dieschnittstelle.jee.esa.uebungen.add3.AbstractProduct arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getPointsOfSale", targetNamespace = "http://dieschnittstelle.org/jee/esa/uebungen/add3", className = "org.dieschnittstelle.jee.esa.uebungen.add3.GetPointsOfSale")
    @WebMethod
    @ResponseWrapper(localName = "getPointsOfSaleResponse", targetNamespace = "http://dieschnittstelle.org/jee/esa/uebungen/add3", className = "org.dieschnittstelle.jee.esa.uebungen.add3.GetPointsOfSaleResponse")
    public java.util.List<java.lang.Integer> getPointsOfSale(
        @WebParam(name = "arg0", targetNamespace = "")
        org.dieschnittstelle.jee.esa.uebungen.add3.AbstractProduct arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getTotalUnitsOnStock", targetNamespace = "http://dieschnittstelle.org/jee/esa/uebungen/add3", className = "org.dieschnittstelle.jee.esa.uebungen.add3.GetTotalUnitsOnStock")
    @WebMethod
    @ResponseWrapper(localName = "getTotalUnitsOnStockResponse", targetNamespace = "http://dieschnittstelle.org/jee/esa/uebungen/add3", className = "org.dieschnittstelle.jee.esa.uebungen.add3.GetTotalUnitsOnStockResponse")
    public int getTotalUnitsOnStock(
        @WebParam(name = "arg0", targetNamespace = "")
        org.dieschnittstelle.jee.esa.uebungen.add3.AbstractProduct arg0
    );

    @RequestWrapper(localName = "removeFromStock", targetNamespace = "http://dieschnittstelle.org/jee/esa/uebungen/add3", className = "org.dieschnittstelle.jee.esa.uebungen.add3.RemoveFromStock")
    @WebMethod
    @ResponseWrapper(localName = "removeFromStockResponse", targetNamespace = "http://dieschnittstelle.org/jee/esa/uebungen/add3", className = "org.dieschnittstelle.jee.esa.uebungen.add3.RemoveFromStockResponse")
    public void removeFromStock(
        @WebParam(name = "arg0", targetNamespace = "")
        org.dieschnittstelle.jee.esa.uebungen.add3.AbstractProduct arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAllProductsOnStock", targetNamespace = "http://dieschnittstelle.org/jee/esa/uebungen/add3", className = "org.dieschnittstelle.jee.esa.uebungen.add3.GetAllProductsOnStock")
    @WebMethod
    @ResponseWrapper(localName = "getAllProductsOnStockResponse", targetNamespace = "http://dieschnittstelle.org/jee/esa/uebungen/add3", className = "org.dieschnittstelle.jee.esa.uebungen.add3.GetAllProductsOnStockResponse")
    public java.util.List<org.dieschnittstelle.jee.esa.uebungen.add3.AbstractProduct> getAllProductsOnStock();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getProductsOnStock", targetNamespace = "http://dieschnittstelle.org/jee/esa/uebungen/add3", className = "org.dieschnittstelle.jee.esa.uebungen.add3.GetProductsOnStock")
    @WebMethod
    @ResponseWrapper(localName = "getProductsOnStockResponse", targetNamespace = "http://dieschnittstelle.org/jee/esa/uebungen/add3", className = "org.dieschnittstelle.jee.esa.uebungen.add3.GetProductsOnStockResponse")
    public java.util.List<org.dieschnittstelle.jee.esa.uebungen.add3.AbstractProduct> getProductsOnStock(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );
}
