package org.dieschnittstelle.jee.esa.uebungen.add2;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2015-01-22T22:27:49.027+01:00
 * Generated source version: 2.4.6
 * 
 */
@WebServiceClient(name = "ProductEjbCRUDWebService", 
                  wsdlLocation = "http://localhost:8080/org.dieschnittstelle.jee.esa.shared.ejbmodule.erp/ProductEjbCRUDWebService/ProductCRUDStateless?wsdl",
                  targetNamespace = "http://dieschnittstelle.org/jee/esa/uebungen/add2") 
public class ProductEjbCRUDWebService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://dieschnittstelle.org/jee/esa/uebungen/add2", "ProductEjbCRUDWebService");
    public final static QName ProductCRUDStatelessPort = new QName("http://dieschnittstelle.org/jee/esa/uebungen/add2", "ProductCRUDStatelessPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/org.dieschnittstelle.jee.esa.shared.ejbmodule.erp/ProductEjbCRUDWebService/ProductCRUDStateless?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ProductEjbCRUDWebService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/org.dieschnittstelle.jee.esa.shared.ejbmodule.erp/ProductEjbCRUDWebService/ProductCRUDStateless?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ProductEjbCRUDWebService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ProductEjbCRUDWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProductEjbCRUDWebService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ProductEjbCRUDWebService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ProductEjbCRUDWebService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ProductEjbCRUDWebService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ProductCRUDStateless
     */
    @WebEndpoint(name = "ProductCRUDStatelessPort")
    public ProductCRUDStateless getProductCRUDStatelessPort() {
        return super.getPort(ProductCRUDStatelessPort, ProductCRUDStateless.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProductCRUDStateless
     */
    @WebEndpoint(name = "ProductCRUDStatelessPort")
    public ProductCRUDStateless getProductCRUDStatelessPort(WebServiceFeature... features) {
        return super.getPort(ProductCRUDStatelessPort, ProductCRUDStateless.class, features);
    }

}
