package org.dieschnittstelle.jee.esa.uebungen.add2;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2015-01-22T22:27:48.993+01:00
 * Generated source version: 2.4.6
 * 
 */
@WebService(targetNamespace = "http://dieschnittstelle.org/jee/esa/uebungen/add2", name = "ProductCRUDStateless")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ProductCRUDStateless {

    @WebResult(name = "readAllProductsResponse", targetNamespace = "http://dieschnittstelle.org/jee/esa/uebungen/add2", partName = "readAllProductsResponse")
    @WebMethod
    public AbstractProductArray readAllProducts();

    @WebResult(name = "deleteProductResponse", targetNamespace = "http://dieschnittstelle.org/jee/esa/uebungen/add2", partName = "deleteProductResponse")
    @WebMethod
    public boolean deleteProduct(
        @WebParam(partName = "deleteProduct", name = "deleteProduct", targetNamespace = "http://dieschnittstelle.org/jee/esa/uebungen/add2")
        int deleteProduct
    );

    @WebResult(name = "readProductResponse", targetNamespace = "http://dieschnittstelle.org/jee/esa/uebungen/add2", partName = "readProductResponse")
    @WebMethod
    public AbstractProduct readProduct(
        @WebParam(partName = "readProduct", name = "readProduct", targetNamespace = "http://dieschnittstelle.org/jee/esa/uebungen/add2")
        int readProduct
    );

    @WebResult(name = "updateProductResponse", targetNamespace = "http://dieschnittstelle.org/jee/esa/uebungen/add2", partName = "updateProductResponse")
    @WebMethod
    public AbstractProduct updateProduct(
        @WebParam(partName = "updateProduct", name = "updateProduct", targetNamespace = "http://dieschnittstelle.org/jee/esa/uebungen/add2")
        AbstractProduct updateProduct
    );

    @WebResult(name = "createProductResponse", targetNamespace = "http://dieschnittstelle.org/jee/esa/uebungen/add2", partName = "createProductResponse")
    @WebMethod
    public AbstractProduct createProduct(
        @WebParam(partName = "createProduct", name = "createProduct", targetNamespace = "http://dieschnittstelle.org/jee/esa/uebungen/add2")
        AbstractProduct createProduct
    );
}
